// Comprehensive mapping of currency codes to full English names and ISO country codes (for FlagCDN)
export const CURRENCY_MAP = {
  AED: { name: "UAE Dirham", country: "ae" },
  AFN: { name: "Afghan Afghani", country: "af" },
  ALL: { name: "Albanian Lek", country: "al" },
  AMD: { name: "Armenian Dram", country: "am" },
  AOA: { name: "Angolan Kwanza", country: "ao" },
  ARS: { name: "Argentine Peso", country: "ar" },
  AUD: { name: "Australian Dollar", country: "au" },
  AWG: { name: "Aruban Florin", country: "aw" },
  AZN: { name: "Azerbaijani Manat", country: "az" },
  BAM: { name: "Bosnia & Herzegovina Convertible Mark", country: "ba" },
  BBD: { name: "Barbadian Dollar", country: "bb" },
  BDT: { name: "Bangladeshi Taka", country: "bd" },
  BGN: { name: "Bulgarian Lev", country: "bg" },
  BHD: { name: "Bahraini Dinar", country: "bh" },
  BIF: { name: "Burundian Franc", country: "bi" },
  BMD: { name: "Bermudian Dollar", country: "bm" },
  BND: { name: "Brunei Dollar", country: "bn" },
  BOB: { name: "Bolivian Boliviano", country: "bo" },
  BRL: { name: "Brazilian Real", country: "br" },
  BSD: { name: "Bahamian Dollar", country: "bs" },
  BTN: { name: "Bhutanese Ngultrum", country: "bt" },
  BWP: { name: "Botswana Pula", country: "bw" },
  BYN: { name: "Belarusian Ruble", country: "by" },
  BZD: { name: "Belize Dollar", country: "bz" },
  CAD: { name: "Canadian Dollar", country: "ca" },
  CDF: { name: "Congolese Franc", country: "cd" },
  CHF: { name: "Swiss Franc", country: "ch" },
  CLP: { name: "Chilean Peso", country: "cl" },
  CNY: { name: "Chinese Yuan", country: "cn" },
  COP: { name: "Colombian Peso", country: "co" },
  CRC: { name: "Costa Rican Colón", country: "cr" },
  CUP: { name: "Cuban Peso", country: "cu" },
  CVE: { name: "Cape Verdean Escudo", country: "cv" },
  CZK: { name: "Czech Koruna", country: "cz" },
  DJF: { name: "Djiboutian Franc", country: "dj" },
  DKK: { name: "Danish Krone", country: "dk" },
  DOP: { name: "Dominican Peso", country: "do" },
  DZD: { name: "Algerian Dinar", country: "dz" },
  EGP: { name: "Egyptian Pound", country: "eg" },
  ERN: { name: "Eritrean Nakfa", country: "er" },
  ETB: { name: "Ethiopian Birr", country: "et" },
  EUR: { name: "Euro", country: "eu" },
  FJD: { name: "Fijian Dollar", country: "fj" },
  FKP: { name: "Falkland Islands Pound", country: "fk" },
  FOK: { name: "Faroese Króna", country: "fo" },
  GBP: { name: "British Pound Sterling", country: "gb" },
  GEL: { name: "Georgian Lari", country: "ge" },
  GGP: { name: "Guernsey Pound", country: "gg" },
  GHS: { name: "Ghanaian Cedi", country: "gh" },
  GIP: { name: "Gibraltar Pound", country: "gi" },
  GMD: { name: "Gambian Dalasi", country: "gm" },
  GNF: { name: "Guinean Franc", country: "gn" },
  GTQ: { name: "Guatemalan Quetzal", country: "gt" },
  GYD: { name: "Guyanese Dollar", country: "gy" },
  HKD: { name: "Hong Kong Dollar", country: "hk" },
  HNL: { name: "Honduran Lempira", country: "hn" },
  HRK: { name: "Croatian Kuna", country: "hr" },
  HTG: { name: "Haitian Gourde", country: "ht" },
  HUF: { name: "Hungarian Forint", country: "hu" },
  IDR: { name: "Indonesian Rupiah", country: "id" },
  ILS: { name: "Israeli New Shekel", country: "il" },
  IMP: { name: "Isle of Man Pound", country: "im" },
  INR: { name: "Indian Rupee", country: "in" },
  IQD: { name: "Iraqi Dinar", country: "iq" },
  IRR: { name: "Iranian Rial", country: "ir" },
  ISK: { name: "Icelandic Króna", country: "is" },
  JEP: { name: "Jersey Pound", country: "je" },
  JMD: { name: "Jamaican Dollar", country: "jm" },
  JOD: { name: "Jordanian Dinar", country: "jo" },
  JPY: { name: "Japanese Yen", country: "jp" },
  KES: { name: "Kenyan Shilling", country: "ke" },
  KGS: { name: "Kyrgyzstani Som", country: "kg" },
  KHR: { name: "Cambodian Riel", country: "kh" },
  KID: { name: "Kiribati Dollar", country: "ki" },
  KMF: { name: "Comorian Franc", country: "km" },
  KRW: { name: "South Korean Won", country: "kr" },
  KWD: { name: "Kuwaiti Dinar", country: "kw" },
  KYD: { name: "Cayman Islands Dollar", country: "ky" },
  KZT: { name: "Kazakhstani Tenge", country: "kz" },
  LAK: { name: "Lao Kip", country: "la" },
  LBP: { name: "Lebanese Pound", country: "lb" },
  LKR: { name: "Sri Lankan Rupee", country: "lk" },
  LRD: { name: "Liberian Dollar", country: "lr" },
  LSL: { name: "Lesotho Loti", country: "ls" },
  LYD: { name: "Libyan Dinar", country: "ly" },
  MAD: { name: "Moroccan Dirham", country: "ma" },
  MDL: { name: "Moldovan Leu", country: "md" },
  MGA: { name: "Malagasy Ariary", country: "mg" },
  MKD: { name: "Macedonian Denar", country: "mk" },
  MMK: { name: "Myanmar Kyat", country: "mm" },
  MNT: { name: "Mongolian Tughrik", country: "mn" },
  MOP: { name: "Macanese Pataca", country: "mo" },
  MRU: { name: "Mauritanian Ouguiya", country: "mr" },
  MUR: { name: "Mauritian Rupee", country: "mu" },
  MVR: { name: "Maldivian Rufiyaa", country: "mv" },
  MWK: { name: "Malawian Kwacha", country: "mw" },
  MXN: { name: "Mexican Peso", country: "mx" },
  MYR: { name: "Malaysian Ringgit", country: "my" },
  MZN: { name: "Mozambican Metical", country: "mz" },
  NAD: { name: "Namibian Dollar", country: "na" },
  NGN: { name: "Nigerian Naira", country: "ng" },
  NIO: { name: "Nicaraguan Córdoba", country: "ni" },
  NOK: { name: "Norwegian Krone", country: "no" },
  NPR: { name: "Nepalese Rupee", country: "np" },
  NZD: { name: "New Zealand Dollar", country: "nz" },
  OMR: { name: "Omani Rial", country: "om" },
  PAB: { name: "Panamanian Balboa", country: "pa" },
  PEN: { name: "Peruvian Sol", country: "pe" },
  PGK: { name: "Papua New Guinean Kina", country: "pg" },
  PHP: { name: "Philippine Peso", country: "ph" },
  PKR: { name: "Pakistani Rupee", country: "pk" },
  PLN: { name: "Polish Zloty", country: "pl" },
  PYG: { name: "Paraguayan Guaraní", country: "py" },
  QAR: { name: "Qatari Riyal", country: "qa" },
  RON: { name: "Romanian Leu", country: "ro" },
  RSD: { name: "Serbian Dinar", country: "rs" },
  RUB: { name: "Russian Ruble", country: "ru" },
  RWF: { name: "Rwandan Franc", country: "rw" },
  SAR: { name: "Saudi Riyal", country: "sa" },
  SBD: { name: "Solomon Islands Dollar", country: "sb" },
  SCR: { name: "Seychellois Rupee", country: "sc" },
  SDG: { name: "Sudanese Pound", country: "sd" },
  SEK: { name: "Swedish Krona", country: "se" },
  SGD: { name: "Singapore Dollar", country: "sg" },
  SHP: { name: "Saint Helena Pound", country: "sh" },
  SLE: { name: "Sierra Leonean Leone", country: "sl" },
  SLL: { name: "Sierra Leonean Leone", country: "sl" },
  SOS: { name: "Somali Shilling", country: "so" },
  SRD: { name: "Surinamese Dollar", country: "sr" },
  SSP: { name: "South Sudanese Pound", country: "ss" },
  STN: { name: "São Tomé and Príncipe Dobra", country: "st" },
  SYP: { name: "Syrian Pound", country: "sy" },
  SZL: { name: "Swazi Lilangeni", country: "sz" },
  THB: { name: "Thai Baht", country: "th" },
  TJS: { name: "Tajikistani Somoni", country: "tj" },
  TMT: { name: "Turkmenistan Manat", country: "tm" },
  TND: { name: "Tunisian Dinar", country: "tn" },
  TOP: { name: "Tongan Paʻanga", country: "to" },
  TRY: { name: "Turkish Lira", country: "tr" },
  TTD: { name: "Trinidad and Tobago Dollar", country: "tt" },
  TVD: { name: "Tuvaluan Dollar", country: "tv" },
  TWD: { name: "New Taiwan Dollar", country: "tw" },
  TZS: { name: "Tanzanian Shilling", country: "tz" },
  UAH: { name: "Ukrainian Hryvnia", country: "ua" },
  UGX: { name: "Ugandan Shilling", country: "ug" },
  USD: { name: "United States Dollar", country: "us" },
  UYU: { name: "Uruguayan Peso", country: "uy" },
  UZS: { name: "Uzbekistan Som", country: "uz" },
  VES: { name: "Venezuelan Bolívar Soberano", country: "ve" },
  VND: { name: "Vietnamese Dong", country: "vn" },
  VUV: { name: "Vanuatu Vatu", country: "vu" },
  WST: { name: "Samoan Tala", country: "ws" },
  XAF: { name: "Central African CFA Franc", country: "cf" },
  XCD: { name: "East Caribbean Dollar", country: "ag" },
  XDR: { name: "Special Drawing Rights", country: "un" },
  XOF: { name: "West African CFA Franc", country: "sn" },
  XPF: { name: "CFP Franc", country: "pf" },
  YER: { name: "Yemeni Rial", country: "ye" },
  ZAR: { name: "South African Rand", country: "za" },
  ZMW: { name: "Zambian Kwacha", country: "zm" },
  ZWL: { name: "Zimbabwean Dollar", country: "zw" }
};

// Gets rich currency details including flag URL and full name
export function getCurrencyInfo(code) {
  const normalized = String(code).toUpperCase();
  const entry = CURRENCY_MAP[normalized];
  if (entry) {
    return {
      code: normalized,
      name: entry.name,
      flagUrl: `https://flagcdn.com/w40/${entry.country}.png`
    };
  }
  // Safe robust fallback for unmapped currencies
  return {
    code: normalized,
    name: `${normalized} Currency`,
    flagUrl: "https://flagcdn.com/w40/un.png" // United Nations flag as placeholder
  };
}
